#!/usr/bin/env bash
set -euo pipefail

SOURCE_ENV="${1:-/etc/project-mai-tai/project-mai-tai.env}"
TARGET_ENV="${2:-/etc/project-mai-tai/orb-paper.env}"

if [[ ! -r "$SOURCE_ENV" ]]; then
  echo "ORB paper env refused: source is not readable: $SOURCE_ENV" >&2
  exit 1
fi

mkdir -p "$(dirname "$TARGET_ENV")"
umask 077
tmp="$(mktemp "${TARGET_ENV}.tmp.XXXXXX")"
trap 'rm -f "$tmp"' EXIT

{
  echo "# Generated by build_orb_paper_env.sh. Broker credentials are intentionally excluded."
  while IFS= read -r line || [[ -n "$line" ]]; do
    if [[ ! "$line" =~ ^[[:space:]]*(export[[:space:]]+)?(MAI_TAI_[A-Z0-9_]+)= ]]; then
      continue
    fi
    key="${BASH_REMATCH[2]}"
    case "$key" in
      MAI_TAI_ORB_BROKER_ACCOUNT_NAME|MAI_TAI_ORB_BROKER_PROVIDER)
        ;;
      MAI_TAI_ENVIRONMENT|MAI_TAI_LOG_LEVEL|MAI_TAI_DATABASE_URL|MAI_TAI_REDIS_URL|\
      MAI_TAI_REDIS_STREAM_PREFIX|MAI_TAI_REDIS_MARKET_DATA_SUBSCRIPTION_STREAM_MAXLEN|\
      MAI_TAI_REDIS_STRATEGY_STATE_ISOLATED_STREAM_MAXLEN|MAI_TAI_SERVICE_DB_*|MAI_TAI_ORB_*)
        [[ "$key" == "MAI_TAI_ORB_ENABLED" ]] || printf '%s=%s\n' "$key" "${line#*=}"
        ;;
    esac
  done < "$SOURCE_ENV"
  # This switch starts market-data observation only. Broker isolation is structural.
  echo "MAI_TAI_ORB_ENABLED=true"
} > "$tmp"

chmod 0600 "$tmp"
mv -f "$tmp" "$TARGET_ENV"
trap - EXIT
